import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

// import 'core/router/app_router.dart';
// import 'core/theme/app_theme.dart';                 // from step11_dark_mode
// import 'features/auth/presentation/providers/auth_providers.dart';
// import 'features/settings/presentation/providers/theme_providers.dart';
// import 'features/settings/presentation/viewmodels/theme_viewmodel.dart';
// import 'firebase_options.dart';                     // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase ──────────────────────────────────────────────────────────────
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  // ── SharedPreferences ─────────────────────────────────────────────────────
  final prefs = await SharedPreferences.getInstance();

  runApp(
    ProviderScope(
      overrides: [
        // Theme preference (from step11_dark_mode)
        // sharedPreferencesProvider.overrideWithValue(prefs),
        // Multi-store active branch (from step11_advanced_features)
        // sharedPreferencesProvider.overrideWithValue(prefs),
      ],
      child: const PharmacyApp(),
    ),
  );
}

class PharmacyApp extends ConsumerWidget {
  const PharmacyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // final router    = ref.watch(appRouterProvider);
    // final themeMode = ref.watch(themeViewModelProvider);

    return MaterialApp(
      title: 'PharmaCare',
      debugShowCheckedModeBanner: false,
      // theme:     AppTheme.light,
      // darkTheme: AppTheme.dark,
      // themeMode: themeMode.toFlutterThemeMode(),
      // routerConfig: router,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF1565C0)),
      ),
      home: const Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.local_pharmacy_rounded,
                  size: 60, color: Color(0xFF1565C0)),
              SizedBox(height: 16),
              Text('PharmaCare',
                  style: TextStyle(
                      fontSize: 24, fontWeight: FontWeight.w800,
                      color: Color(0xFF1A1A2E))),
              SizedBox(height: 8),
              Text('Uncomment imports in main.dart to activate routing',
                  style: TextStyle(
                      fontSize: 12, color: Color(0xFF888888))),
            ],
          ),
        ),
      ),
    );
  }