import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../entities/purchase_order_entity.dart';
import '../repositories/inventory_repository.dart';

// ── Get all POs ───────────────────────────────────────────────────────────────

class GetPurchaseOrdersUseCase
    implements UseCase<List<PurchaseOrderEntity>, NoParams> {
  const GetPurchaseOrdersUseCase(this._repo);
  final InventoryRepository _repo;

  @override
  Future<Either<Failure, List<PurchaseOrderEntity>>> call(NoParams _) =>
      _repo.getPurchaseOrders();
}

// ── Create PO ─────────────────────────────────────────────────────────────────

class CreatePurchaseOrderUseCase
    implements UseCase<PurchaseOrderEntity, CreatePOParams> {
  const CreatePurchaseOrderUseCase(this._repo);
  final InventoryRepository _repo;

  @override
  Future<Either<Failure, PurchaseOrderEntity>> call(CreatePOParams p) async {
    if (p.supplierId.trim().isEmpty) {
      return const Left(ValidationFailure('Supplier is required.'));
    }
    if (p.items.isEmpty) {
      return const Left(ValidationFailure('Add at least one item to the order.'));
    }
    for (final item in p.items) {
      if (item.orderedQty <= 0) {
        return Left(ValidationFailure(
            'Quantity for ${item.tradeName} must be greater than 0.'));
      }
      if (item.unitPrice <= 0) {
        return Left(ValidationFailure(
            'Price for ${item.tradeName} must be greater than 0.'));
      }
    }

    final po = PurchaseOrderEntity(
      id: '',
      poNumber: '',         // generated by Firestore / Cloud Function
      supplierId: p.supplierId,
      supplierName: p.supplierName,
      items: p.items,
      status: POStatus.draft,
      createdBy: p.createdBy,
      createdAt: DateTime.now(),
      notes: p.notes,
      expectedDate: p.expectedDate,
    );

    return _repo.createPurchaseOrder(po);
  }
}

class CreatePOParams extends Equatable {
  const CreatePOParams({
    required this.supplierId,
    required this.supplierName,
    required this.items,
    required this.createdBy,
    this.notes,
    this.expectedDate,
  });

  final String supplierId;
  final String supplierName;
  final List<POItem> items;
  final String createdBy;
  final String? notes;
  final DateTime? expectedDate;

  @override
  List<Object?> get props => [supplierId, items, createdBy];
}

// ── Receive PO (GRN) ──────────────────────────────────────────────────────────

class ReceivePurchaseOrderUseCase
    implements UseCase<PurchaseOrderEntity, ReceivePOParams> {
  const ReceivePurchaseOrderUseCase(this._repo);
  final InventoryRepository _repo;

  @override
  Future<Either<Failure, PurchaseOrderEntity>> call(ReceivePOParams p) async {
    if (p.poId.isEmpty) {
      return const Left(ValidationFailure('PO ID is required.'));
    }
    if (p.receivedItems.isEmpty) {
      return const Left(ValidationFailure('No items marked as received.'));
    }
    for (final item in p.receivedItems) {
      if (item.receivedQty < 0) {
        return Left(ValidationFailure(
            'Received qty for ${item.tradeName} cannot be negative.'));
      }
      if (item.expiryDate == null) {
        return Left(ValidationFailure(
            'Expiry date required for ${item.tradeName}.'));
      }
      if (item.batchNo == null || item.batchNo!.isEmpty) {
        return Left(ValidationFailure(
            'Batch number required for ${item.tradeName}.'));
      }
    }

    return _repo.receivePurchaseOrder(
      poId: p.poId,
      receivedItems: p.receivedItems,
      receivedBy: p.receivedBy,
    );
  }
}

class ReceivePOParams extends Equatable {
  const ReceivePOParams({
    required this.poId,
    required this.receivedItems,
    required this.receivedBy,
  });

  final String poId;
  final List<POItem> receivedItems;
  final String receivedBy;

  @override
  List<Object?> get props => [poId, receivedItems, receivedBy];
}

// ── Cancel PO ─────────────────────────────────────────────────────────────────

class CancelPurchaseOrderUseCase implements UseCase<void, CancelPOParams> {
  const CancelPurchaseOrderUseCase(this._repo);
  final InventoryRepository _repo;

  @override
  Future<Either<Failure, void>> call(CancelPOParams p) {
    if (p.id.isEmpty) {
      return Future.value(const Left(ValidationFailure('PO ID required.')));
    }
    return _repo.cancelPurchaseOrder(p.id);
  }
}

class CancelPOParams extends Equatable {
  const CancelPOParams(this.id);
  final String id;
  @override
  List<Object> get props => [id];
}